spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_dockers_prova
    username: jmg
    password: jmg
    initialize: false

---
spring:
  #jackson:
    #serialization:
      #INDENT_OUTPUT: true
  #profiles: container
  #jpa:
    #hibernate:
      #ddl-auto: create
  datasource:
    password: "${DATABASE_PASSWORD}"
    url: "jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
    username: "${DATABASE_USER}"
    initialize: true
server:
  contextPath: